INSERT INTO BMTC_ODS.CustomerLocation (CustomerID, Address, Region, LastUpdate) 
VALUES (1, 'Address_1', 'North America', CURRENT_TIMESTAMP)
      ,(1, 'Address_2', 'South America', CURRENT_TIMESTAMP)
      ,(4, 'Address_3', 'Europe', CURRENT_TIMESTAMP)
      ,(5, 'Address_4', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(6, 'Address_5', 'North America', CURRENT_TIMESTAMP)
      ,(7, 'Address_6', 'North America', CURRENT_TIMESTAMP)
      ,(8, 'Address_7', 'South America', CURRENT_TIMESTAMP)
      ,(9, 'Address_8', 'Europe', CURRENT_TIMESTAMP)
      ,(10, 'Address_9', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(11, 'Address_10', 'North America', CURRENT_TIMESTAMP)
      ,(12, 'Address_11', 'North America', CURRENT_TIMESTAMP)
      ,(13, 'Address_12', 'South America', CURRENT_TIMESTAMP)
      ,(14, 'Address_13', 'Europe', CURRENT_TIMESTAMP)
      ,(15, 'Address_14', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(16, 'Address_15', 'North America', CURRENT_TIMESTAMP)
      ,(17, 'Address_16', 'North America', CURRENT_TIMESTAMP)
      ,(18, 'Address_17', 'South America', CURRENT_TIMESTAMP)
      ,(19, 'Address_18', 'Europe', CURRENT_TIMESTAMP)
      ,(20, 'Address_19', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(21, 'Address_20', 'North America', CURRENT_TIMESTAMP)
      ,(22, 'Address_21', 'North America', CURRENT_TIMESTAMP)
      ,(23, 'Address_22', 'South America', CURRENT_TIMESTAMP)
      ,(24, 'Address_23', 'Europe', CURRENT_TIMESTAMP)
      ,(25, 'Address_24', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(26, 'Address_25', 'North America', CURRENT_TIMESTAMP)
      ,(27, 'Address_26', 'North America', CURRENT_TIMESTAMP)
      ,(28, 'Address_27', 'South America', CURRENT_TIMESTAMP)
      ,(29, 'Address_28', 'Europe', CURRENT_TIMESTAMP)
      ,(30, 'Address_29', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(31, 'Address_30', 'North America', CURRENT_TIMESTAMP)
      ,(32, 'Address_31', 'North America', CURRENT_TIMESTAMP)
      ,(33, 'Address_32', 'South America', CURRENT_TIMESTAMP)
      ,(34, 'Address_33', 'Europe', CURRENT_TIMESTAMP)
      ,(35, 'Address_34', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(36, 'Address_35', 'North America', CURRENT_TIMESTAMP)
      ,(37, 'Address_36', 'North America', CURRENT_TIMESTAMP)
      ,(38, 'Address_37', 'South America', CURRENT_TIMESTAMP)
      ,(39, 'Address_38', 'Europe', CURRENT_TIMESTAMP)
      ,(40, 'Address_39', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(41, 'Address_40', 'North America', CURRENT_TIMESTAMP)
      ,(42, 'Address_41', 'North America', CURRENT_TIMESTAMP)
      ,(43, 'Address_42', 'South America', CURRENT_TIMESTAMP)
      ,(44, 'Address_43', 'Europe', CURRENT_TIMESTAMP)
      ,(45, 'Address_44', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(46, 'Address_45', 'North America', CURRENT_TIMESTAMP)
      ,(47, 'Address_46', 'North America', CURRENT_TIMESTAMP)
      ,(48, 'Address_47', 'South America', CURRENT_TIMESTAMP)
      ,(49, 'Address_48', 'Europe', CURRENT_TIMESTAMP)
      ,(50, 'Address_49', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(51, 'Address_50', 'North America', CURRENT_TIMESTAMP)
      ,(52, 'Address_51', 'North America', CURRENT_TIMESTAMP)
      ,(53, 'Address_52', 'South America', CURRENT_TIMESTAMP)
      ,(54, 'Address_53', 'Europe', CURRENT_TIMESTAMP)
      ,(55, 'Address_54', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(56, 'Address_55', 'North America', CURRENT_TIMESTAMP)
      ,(57, 'Address_56', 'North America', CURRENT_TIMESTAMP)
      ,(58, 'Address_57', 'South America', CURRENT_TIMESTAMP)
      ,(59, 'Address_58', 'Europe', CURRENT_TIMESTAMP)
      ,(60, 'Address_59', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(61, 'Address_60', 'North America', CURRENT_TIMESTAMP)
      ,(62, 'Address_61', 'North America', CURRENT_TIMESTAMP)
      ,(63, 'Address_62', 'South America', CURRENT_TIMESTAMP)
      ,(64, 'Address_63', 'Europe', CURRENT_TIMESTAMP)
      ,(65, 'Address_64', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(66, 'Address_65', 'North America', CURRENT_TIMESTAMP)
      ,(67, 'Address_66', 'North America', CURRENT_TIMESTAMP)
      ,(68, 'Address_67', 'South America', CURRENT_TIMESTAMP)
      ,(69, 'Address_68', 'Europe', CURRENT_TIMESTAMP)
      ,(70, 'Address_69', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(71, 'Address_70', 'North America', CURRENT_TIMESTAMP)
      ,(72, 'Address_71', 'North America', CURRENT_TIMESTAMP)
      ,(73, 'Address_72', 'South America', CURRENT_TIMESTAMP)
      ,(74, 'Address_73', 'Europe', CURRENT_TIMESTAMP)
      ,(75, 'Address_74', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(76, 'Address_75', 'North America', CURRENT_TIMESTAMP)
      ,(77, 'Address_76', 'North America', CURRENT_TIMESTAMP)
      ,(78, 'Address_77', 'South America', CURRENT_TIMESTAMP)
      ,(79, 'Address_78', 'Europe', CURRENT_TIMESTAMP)
      ,(80, 'Address_79', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(81, 'Address_80', 'North America', CURRENT_TIMESTAMP)
      ,(82, 'Address_81', 'North America', CURRENT_TIMESTAMP)
      ,(83, 'Address_82', 'South America', CURRENT_TIMESTAMP)
      ,(84, 'Address_83', 'Europe', CURRENT_TIMESTAMP)
      ,(85, 'Address_84', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(86, 'Address_85', 'North America', CURRENT_TIMESTAMP)
      ,(87, 'Address_86', 'North America', CURRENT_TIMESTAMP)
      ,(88, 'Address_87', 'South America', CURRENT_TIMESTAMP)
      ,(89, 'Address_88', 'Europe', CURRENT_TIMESTAMP)
      ,(90, 'Address_89', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(91, 'Address_90', 'North America', CURRENT_TIMESTAMP)
      ,(92, 'Address_91', 'North America', CURRENT_TIMESTAMP)
      ,(93, 'Address_92', 'South America', CURRENT_TIMESTAMP)
      ,(94, 'Address_93', 'Europe', CURRENT_TIMESTAMP)
      ,(95, 'Address_94', 'Asia-Pacific', CURRENT_TIMESTAMP)
      ,(96, 'Address_95', 'North America', CURRENT_TIMESTAMP)
      ,(97, 'Address_96', 'North America', CURRENT_TIMESTAMP)
      ,(98, 'Address_97', 'South America', CURRENT_TIMESTAMP)
      ,(99, 'Address_98', 'Europe', CURRENT_TIMESTAMP)