INSERT INTO BMTC_ODS.ProductCategory (CategoryName, SubCategoryName, Material, LastUpdate) 
VALUES ('Structural', 'Structural Steel', 'Steel', CURRENT_TIMESTAMP),
       ('Structural', 'Rebar', 'Steel', CURRENT_TIMESTAMP),
	   ('Structural', 'Reinforced Concrete', 'Concrete', CURRENT_TIMESTAMP),
	   ('Structural', 'Lumber', 'Wood', CURRENT_TIMESTAMP),
	   ('Structural', 'Plywood', 'Wood',  CURRENT_TIMESTAMP),
	   ('Plumbing', 'Waterproofing Membranes', NULL, CURRENT_TIMESTAMP),
	   ('Plumbing', 'Plumbing Fixtures', NULL, CURRENT_TIMESTAMP),
	   ('Electrical', 'Wiring', 'Copper', CURRENT_TIMESTAMP),
	   ('Electrical', 'Circuit Breakers', NULL, CURRENT_TIMESTAMP),
	   ('Electrical', 'Lighting Fixtures', NULL, CURRENT_TIMESTAMP),
	   ('HVAC', 'Air Conditioning Units', NULL, CURRENT_TIMESTAMP),
	   ('HVAC', 'Heating Systems', NULL, CURRENT_TIMESTAMP),
	   ('HVAC', 'Ventilation Systems', NULL, CURRENT_TIMESTAMP),
	   ('Finishing', 'Drywall', 'Gypsum Board', CURRENT_TIMESTAMP),
	   ('Finishing', 'Flooring', 'Tile', CURRENT_TIMESTAMP),
	   ('Finishing', 'Flooring', 'Carpet', CURRENT_TIMESTAMP),
	   ('Finishing', 'Trim', 'Wood', CURRENT_TIMESTAMP),
	   ('Finishing', 'Wallpaper', 'Paper', CURRENT_TIMESTAMP),
	   ('Roofing', 'Shingles', 'Asphalt', CURRENT_TIMESTAMP),
	   ('Roofing', 'Shingles', 'Wood', CURRENT_TIMESTAMP),
	   ('Roofing', 'Shingles', 'Slate', CURRENT_TIMESTAMP),
	   ('Roofing', 'Shingles', 'Metal', CURRENT_TIMESTAMP),
;
